Repository trento-project/agent, pull requests merged in 2022-11, with the labels that each got.

#142 Coveralls
  .github/dependabot.yaml
  .github/workflows/ci.yaml
  .github/workflows/dependabot_auto_merge.yaml
  .gitignore
  Makefile
  README.md
Labels: github_actions, chore, test, dx

#139 Port systemd gatherer
  internal/factsengine/gatherers/corosyncconf.go
  internal/factsengine/gatherers/gatherer.go
  internal/factsengine/gatherers/hostsfile.go
  internal/factsengine/gatherers/registry_test.go
  internal/factsengine/gatherers/systemd.go
  internal/factsengine/gatherers/systemd_test.go
Labels: enhancement

#140 Packageversion gatherer
  internal/factsengine/gatherers/_todo/packageversion.go
  internal/factsengine/gatherers/gatherer.go
  internal/factsengine/gatherers/packageversion.go
  internal/factsengine/gatherers/packageversion_test.go
Labels: enhancement

#141 Refactor sbd gatherer
  internal/cluster/sbd_test.go
  internal/factsengine/gatherers/_todo/sbd.go
  internal/factsengine/gatherers/_todo/sbd_test.go
  internal/factsengine/gatherers/gatherer.go
  internal/factsengine/gatherers/sbd.go
  internal/factsengine/gatherers/sbd_test.go
  test/fixtures/discovery/cluster/expected_published_cluster_discovery.json
  test/fixtures/discovery/cluster/sbd/sbd_config
  test/fixtures/discovery/cluster/sbd/sbd_config_invalid
Labels: enhancement, tech debt

#145 Refactor sbd loading
  internal/cluster/sbd.go
  internal/cluster/sbd_test.go
  internal/factsengine/gatherers/sbd.go
  internal/factsengine/gatherers/sbd_test.go
  test/fixtures/discovery/cluster/expected_published_cluster_discovery.json
Labels: tech debt
