Repository trento-project/agent, pull requests merged in 2023-10, with the labels that each got.

#263 Handle nil value in NewFactValue
  pkg/factsengine/entities/fact_value.go
  pkg/factsengine/entities/fact_value_test.go
Labels: enhancement

#267 Sap profile gatherer
  internal/core/sapsystem/sapsystem.go
  internal/core/sapsystem/sapsystem_test.go
  internal/factsengine/gatherers/gatherer.go
  internal/factsengine/gatherers/sapprofiles.go
  internal/factsengine/gatherers/sapprofiles_test.go
  test/fixtures/gatherers/sap_profile.ascs
  test/fixtures/gatherers/sap_profile.default
  test/fixtures/gatherers/sap_profile.minimal
Labels: enhancement

#269 Dir scan gatherer
  internal/factsengine/gatherers/credentials_fetcher.go
  internal/factsengine/gatherers/dir_scan.go
  internal/factsengine/gatherers/dir_scan_test.go
  internal/factsengine/gatherers/gatherer.go
  internal/factsengine/gatherers/mocks/GroupSearcher.go
  internal/factsengine/gatherers/mocks/UserSearcher.go
Labels: go

#273 Refactor NewSAPSystemsList to have a default function
  internal/core/sapsystem/sapsystem.go
  internal/core/sapsystem/sapsystem_test.go
  internal/discovery/sapsystem.go
Labels: tech debt

#270 Sapcontrol gatherer
  internal/core/sapsystem/sapcontrolapi/mocks/WebService.go
  internal/core/sapsystem/sapcontrolapi/webservice.go
  internal/factsengine/gatherers/gatherer.go
  internal/factsengine/gatherers/sapcontrol.go
  internal/factsengine/gatherers/sapcontrol_test.go
Labels: enhancement

#277 Gatherers versioning
  internal/factsengine/factsengine_integration_test.go
  internal/factsengine/gatherers/gatherer.go
  internal/factsengine/gatherers/plugin.go
  internal/factsengine/gatherers/plugin_test.go
  internal/factsengine/gatherers/registry.go
  internal/factsengine/gatherers/registry_test.go
  internal/factsengine/gathering_test.go
Labels: enhancement, go

#280 Add .tool-versions file
  .tool-versions
Labels: chore

#278 Systemd V2 gatherer
  internal/factsengine/gatherers/gatherer.go
  internal/factsengine/gatherers/mocks/DbusConnector.go
  internal/factsengine/gatherers/systemd.go
  internal/factsengine/gatherers/systemd_test.go
  internal/factsengine/gatherers/systemd_v2.go
  internal/factsengine/gatherers/systemd_v2_test.go
Labels: enhancement

#281 Disp work gatherer
  internal/factsengine/gatherers/dispwork.go
  internal/factsengine/gatherers/dispwork_test.go
  internal/factsengine/gatherers/gatherer.go
  test/fixtures/gatherers/dispwork-partial.output
  test/fixtures/gatherers/dispwork-unsorted.output
  test/fixtures/gatherers/dispwork-valid.output
Labels: enhancement

#282 Sapservices gatherer
  internal/factsengine/gatherers/gatherer.go
  internal/factsengine/gatherers/sapservices.go
  internal/factsengine/gatherers/sapservices_test.go
Labels: go

#284 Mount info gatherer
  go.mod
  go.sum
  internal/factsengine/gatherers/gatherer.go
  internal/factsengine/gatherers/mocks/MountParserInterface.go
  internal/factsengine/gatherers/mountinfo.go
  internal/factsengine/gatherers/mountinfo_test.go
Labels: enhancement

#285 Products gatherer
  internal/factsengine/gatherers/cibadmin.go
  internal/factsengine/gatherers/gatherer.go
  internal/factsengine/gatherers/products.go
  internal/factsengine/gatherers/products_test.go
  internal/factsengine/gatherers/xml.go
Labels: enhancement
