Repository trento-project/agent, pull requests merged in 2023-08, with the labels that each got.

#235 Release 2.1.0
  CHANGELOG.md
  install-agent.sh
Labels: release

#236 Remove not needed certificates
  test/certs/ca-cert.pem
  test/certs/ca-key.pem
  test/certs/client-cert.pem
  test/certs/client-key.pem
  test/certs/client-req.pem
  test/certs/server-cert.pem
  test/certs/server-key.pem
  test/certs/server-req.pem
Labels: chore

#243 Ignore extra output when comparing versions with zypper
  internal/factsengine/gatherers/packageversion.go
  internal/factsengine/gatherers/packageversion_test.go
  test/fixtures/gatherers/versioncmp-with-warning.output
Labels: bug, enhancement

#246 bump contracts version
  go.mod
  go.sum
Labels: dependencies
