Repository trento-project/agent, pull requests merged in 2024-07, with the labels that each got.

#341 Add pr template for agent repo
  .github/pull_request_template.md
Labels: documentation, tech debt

#334 Fix install-agent.sh with --use-tgz
  install-agent.sh
Labels: bug

#346 Discover host ip address netmasks
  internal/core/hosts/discovered_host.go
  internal/discovery/host.go
  internal/discovery/mocks/discovered_host_mock.go
  test/fixtures/discovery/host/expected_published_host_discovery.json
Labels: enhancement
