Repository trento-project/agent, pull requests merged in 2024-02, with the labels that each got.

#322 Update saptune discovery interval
  cmd/config_test.go
  cmd/start.go
  packaging/config/agent.yaml
  test/fixtures/config/agent.yaml
Labels: documentation, enhancement

#321 Send sbd data in diskless scenario
  internal/core/cluster/cluster.go
  internal/core/cluster/cluster_test.go
  test/fixtures/discovery/cluster/fake_crm_mon_diskless_sbd.sh
Labels: enhancement

#323 Update license year
  README.md
Labels: documentation, chore
