Repository trento-project/agent, pull requests merged in 2025-07, with the labels that each got.

#455 Systemd units discovery
  internal/core/hosts/discovered_host.go
  internal/core/hosts/host.go
  internal/core/hosts/host_test.go
  internal/core/hosts/systemd/dbus.go
  internal/core/hosts/systemd/mocks/mock_DbusConnector.go
  internal/discovery/host.go
  internal/discovery/mocks/discovered_host_mock.go
  test/fixtures/discovery/host/expected_published_host_discovery.json
Labels: enhancement

#457 Add managed field to crm_mon group
  internal/core/cluster/crmmon/data.go
  internal/core/cluster/crmmon/parser_test.go
  test/fixtures/discovery/cluster/expected_published_cluster_discovery.json
  test/fixtures/discovery/cluster/fake_crm_mon.sh
Labels: enhancement

#458 Use latest version of endorama/asdf-parse-tool-versions to avoid using deprecated set-output command in gh actions.
  .github/workflows/ci.yaml
  .github/workflows/obs.yaml
Labels: github_actions, ci

#459 Convert Markdown documentation to Adoc
  CONTRIBUTING.adoc
  CONTRIBUTING.md
  README.adoc
  README.md
  docs/ci-cd-variables.adoc
  docs/ci-cd-variables.md
  docs/development/how-to-make-a-release.adoc
  docs/development/how-to-make-a-release.md
Labels: documentation

#462 Fix link and references for adoc documents
  README.adoc
Labels: bug, documentation
