Repository trento-project/agent, pull requests merged in 2025-03, with the labels that each got.

#405 Upgrade github actions runner ubuntu version
  .github/workflows/ci.yaml
Labels: chore, ci

#406 RabbitMQ Supports SSL Config
  Makefile
  container_fixtures/rabbitmq/certs/ca_certificate.pem
  container_fixtures/rabbitmq/certs/ca_key.pem
  container_fixtures/rabbitmq/certs/client_agent.trento.local_certificate.pem
  container_fixtures/rabbitmq/certs/client_agent.trento.local_key.pem
  container_fixtures/rabbitmq/certs/server_rabbit.trento.local_certificate.pem
  container_fixtures/rabbitmq/certs/server_rabbit.trento.local_key.pem
  container_fixtures/rabbitmq/rabbitmq.conf
  docker-compose.yaml
  go.mod
  go.sum
  internal/factsengine/adapters/adapter.go
  internal/factsengine/adapters/mocks/Adapter.go
  internal/factsengine/adapters/rabbitmq.go
  internal/factsengine/factsengine.go
  internal/factsengine/factsengine_integration_test.go
  internal/factsengine/policy.go
  internal/factsengine/policy_internal_test.go
Labels: enhancement

#416 Identify j2ee instances as application instances
  internal/core/sapsystem/sapinstance.go
  internal/core/sapsystem/sapsystem_test.go
Labels: bug
