Repository trento-project/agent, pull requests merged in 2025-05, with the labels that each got.

#436 Use discoveries as list instead of map to guarantee order
  internal/agent/agent.go
  internal/discovery/policy.go
  internal/discovery/policy_integration_test.go
Labels: bug

#437 Add CODEOWNERS
  .github/CODEOWNERS
  .github/dependabot.yaml
Labels: enhancement

#439 update installation script and readme instructions
  README.md
  install-agent.sh
Labels: documentation, tech debt
