Repository trento-project/agent, pull requests merged in 2025-04, with the labels that each got.

#418 Identify current instance SAP instances
  internal/core/sapsystem/sapcontrol.go
  internal/core/sapsystem/sapcontrolapi/webservice.go
  internal/core/sapsystem/sapinstance.go
  internal/core/sapsystem/sapsystem.go
  internal/core/sapsystem/sapsystem_test.go
  internal/factsengine/gatherers/sapcontrol_test.go
  test/fixtures/discovery/sap_system/expected_published_sap_system_discovery_application.json
  test/fixtures/discovery/sap_system/expected_published_sap_system_discovery_database.json
  test/fixtures/discovery/sap_system/expected_published_sap_system_discovery_diagnostics.json
  test/fixtures/discovery/sap_system/sap_system_discovery_application.json
  test/fixtures/discovery/sap_system/sap_system_discovery_database.json
  test/fixtures/discovery/sap_system/sap_system_discovery_diagnostics.json
Labels: enhancement

#420 Generic event handler and messaging
  go.mod
  go.sum
  internal/factsengine/factsengine.go
  internal/factsengine/factsengine_integration_test.go
  internal/factsengine/policy.go
  internal/factsengine/policy_test.go
  internal/messaging/adapter.go
  internal/messaging/eventhandler.go
  internal/messaging/mocks/Adapter.go
  internal/messaging/rabbitmq.go
Labels: enhancement, chore

#414 Support AWS IMDSv2
  .github/workflows/ci.yaml
  internal/core/cloud/aws.go
  internal/core/cloud/aws_test.go
  internal/core/cloud/metadata.go
  internal/core/cloud/metadata_test.go
  internal/discovery/collector/publishing_test.go
  test/fixtures/discovery/aws/block-device-mapping
  test/fixtures/discovery/aws/collector_payloads/expected_published_cloud_discovery_with_metadata.json
  test/fixtures/discovery/aws/collector_payloads/expected_published_cloud_discovery_without_metadata.json
  test/fixtures/discovery/provider/kvm/expected_published_cloud_discovery.json
  test/fixtures/discovery/provider/nutanix/expected_published_cloud_discovery.json
  test/fixtures/discovery/provider/vmware/expected_published_cloud_discovery.json
Labels: bug, enhancement

#423 Support aws imds v2
  internal/core/cloud/aws.go
  internal/core/cloud/aws_test.go
  internal/core/cloud/metadata.go
  internal/core/cloud/metadata_test.go
  internal/discovery/collector/publishing_test.go
  test/fixtures/discovery/aws/block-device-mapping
  test/fixtures/discovery/aws/collector_payloads/expected_published_cloud_discovery_with_metadata.json
  test/fixtures/discovery/aws/collector_payloads/expected_published_cloud_discovery_without_metadata.json
  test/fixtures/discovery/provider/kvm/expected_published_cloud_discovery.json
  test/fixtures/discovery/provider/nutanix/expected_published_cloud_discovery.json
  test/fixtures/discovery/provider/vmware/expected_published_cloud_discovery.json
Labels: bug, enhancement

#424 Listen discovery requests
  go.mod
  go.sum
  internal/agent/agent.go
  internal/discovery/discovery.go
  internal/discovery/mapper.go
  internal/discovery/mapper_test.go
  internal/discovery/mocks/Discovery.go
  internal/discovery/policy.go
  internal/discovery/policy_integration_test.go
  internal/discovery/policy_test.go
Labels: enhancement

#425 Update packaging and service files for SLES 16
  README.md
  packaging/suse/trento-agent.spec
  packaging/systemd/trento-agent.service
Labels: release
